#!/usr/bin/env bash

# this is a simple config for herbstluftwm

hc() {
    herbstclient "$@"
}

hc emit_hook reload

xsetroot -solid '#5A8E3A'

# remove all existing keybindings
hc keyunbind --all

# keybindings
# if you have a super key you will be much happier with Mod set to Mod4
#Mod=Mod1    # Use alt as the main modifier
Mod=Mod4   # Use the super key as the main modifier
ORANGE='#FB8C00'

hc spawn xset s off
hc spawn xset -dpms

hc keybind $Mod-Shift-e quit
hc keybind $Mod-Shift-r reload
hc keybind $Mod-Shift-q close
hc keybind $Mod-Return spawn termite
# hc keybind $Mod-d spawn rofi -width 1800 -fg "#B0E670" -bg "#2c303b" -hlfg "#14161F" -hlbg "#B0E670" -bc "#2c203b" -location 0 -lines 19 -bw 0 -font "MonacoB 16" -padding 15 -separator-style none -opacity 95 -show drun -modi run,drun,window -show-icons -sidebar-mode
hc keybind $Mod-d spawn rofi -show drun -modi drun,run
hc keybind $Mod-t spawn rofi -show window
hc keybind $Mod-t spawn rofi -modi grab:~/dotfiles/grabwindow.zsh,window -show grab
hc keybind $Mod-y spawn sh ~/.config/rofi/power.sh

# basic movement
# focusing clients
hc keybind $Mod-Left  focus left
hc keybind $Mod-Down  focus down
hc keybind $Mod-Up    focus up
hc keybind $Mod-Right focus right
hc keybind $Mod-h     focus left
hc keybind $Mod-j     focus down
hc keybind $Mod-k     focus up
hc keybind $Mod-l     focus right

# moving clients
hc keybind $Mod-Shift-Left or / shift left / \
    chain , lock , shift_to_monitor -l , focus_monitor -l , unlock
hc keybind $Mod-Shift-Down  or / shift down / \
    chain , lock , shift_to_monitor -d , focus_monitor -d , unlock
hc keybind $Mod-Shift-Up    or / shift up / \
    chain , lock , shift_to_monitor -u , focus_monitor -u , unlock
hc keybind $Mod-Shift-Right or / shift right / \
    chain , lock , shift_to_monitor -r , focus_monitor -r , unlock
#hc keybind $Mod-Shift-h     shift left
#hc keybind $Mod-Shift-j     shift down
#hc keybind $Mod-Shift-k     shift up
#hc keybind $Mod-Shift-l     shift right

# splitting frames
# create an empty frame at the specified direction
hc keybind $Mod-u       split   bottom  0.5
hc keybind $Mod-o       split   right   0.5
# let the current frame explode into subframes
hc keybind $Mod-Control-space split explode

# resizing frames
resizestep=0.05
hc keybind $Mod-Control-h       resize left +$resizestep
hc keybind $Mod-Control-j       resize down +$resizestep
hc keybind $Mod-Control-k       resize up +$resizestep
hc keybind $Mod-Control-l       resize right +$resizestep
hc keybind $Mod-Control-Left    resize left +$resizestep
hc keybind $Mod-Control-Down    resize down +$resizestep
hc keybind $Mod-Control-Up      resize up +$resizestep
hc keybind $Mod-Control-Right   resize right +$resizestep

hc keybind $Mod-Shift-space floating toggle

# tags
tag_names=( {1..9} )
tag_keys=( {1..9} 0 )

hc rename default "${tag_names[0]}" || true
for i in ${!tag_names[@]} ; do
    hc add "${tag_names[$i]}"
    key="${tag_keys[$i]}"
    if ! [ -z "$key" ] ; then
        hc keybind "$Mod-$key" use_index "$i"
        hc keybind "$Mod-Shift-$key" move_index "$i"
    fi
done

# cycle through tags
hc keybind $Mod-period use_index +1 --skip-visible
hc keybind $Mod-comma  use_index -1 --skip-visible

# layouting
hc keybind $Mod-r remove
hc keybind $Mod-s floating toggle
hc keybind $Mod-f fullscreen toggle
hc keybind $Mod-p pseudotile toggle
# The following cycles through the available layouts within a frame, but skips
# layouts, if the layout change wouldn't affect the actual window positions.
# I.e. if there are two windows within a frame, the grid layout is skipped.
hc keybind $Mod-space                                                           \
            or , and . compare tags.focus.curframe_wcount = 2                   \
                     . cycle_layout +1 vertical horizontal max grid    \
               , cycle_layout +1

# mouse
hc mouseunbind --all
hc mousebind $Mod-Button1 move
hc mousebind $Mod-Button2 zoom
hc mousebind $Mod-Button3 resize
hc mousebind Mod1-B4 call substitute WID clients.dragged.winid spawn transset-df --inc -i WID 0.05

# focus
hc keybind $Mod-BackSpace   cycle_monitor
hc keybind $Mod-Tab         cycle_all +1
hc keybind $Mod-Shift-Tab   cycle_all -1
hc keybind $Mod-c cycle
hc keybind $Mod-i jumpto urgent

# theme
hc attr theme.tiling.reset 1
hc attr theme.floating.reset 1
hc set frame_border_active_color '#222222'
hc set frame_border_normal_color '#101010'
hc set frame_bg_normal_color '#565656'
hc set frame_bg_active_color $ORANGE
hc set frame_border_width 1
hc set always_show_frame 1
hc set frame_bg_transparent 1
hc set frame_transparent_width 5
hc set frame_gap 0
hc set frame_active_opactiy 1
hc set frame_normal_opacity 0

hc attr theme.active.color $ORANGE
hc attr theme.normal.color '#454545'
hc attr theme.urgent.color red
hc attr theme.inner_width 0
hc attr theme.inner_color white
hc attr theme.border_width 0
hc attr theme.floating.border_width 4
hc attr theme.floating.outer_width 0
hc attr theme.floating.outer_color black
hc attr theme.active.inner_color '#3E4A00'
hc attr theme.active.outer_color '#3E4A00'
hc attr theme.background_color white #'#141414'

hc set window_gap 10
hc set frame_padding 0
hc set smart_window_surroundings 0
hc set smart_frame_surroundings 0
hc set mouse_recenter_gap 0
#hc set focus_follows_mouse 1

# Media
hc keybind XF86AudioRaiseVolume spawn pactl set-sink-volume @DEFAULT_SINK@ +5%
hc keybind XF86AudioLowerVolume spawn pactl set-sink-volume @DEFAULT_SINK@ -5%

hc keybind XF86AudioPlay spawn mpc toggle #strawberry -t; sh $HOME/dotfiles/musictoggle.sh -u strawberry
hc keybind XF86AudioPause spawn mpc toggle #strawberry -t

# rules
hc unrule -F
#hc rule class=XTerm tag=3 # move all xterms to tag 3
hc rule focus=on # normally focus new clients
# this enables my monitor swapping
hc set swap_monitors_to_get_tag 0
#hc rule focus=off # normally do not focus new clients [get class with xprop]
#hc rule class~'(.*[Rr]xvt.*|.*[Tt]erm|Konsole)' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' pseudotile=on
hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK|DESKTOP)' manage=off
hc rule --title="Slack | mini panel" --floating=on --manage=off

hc set tree_style '╾│ ├└╼─┐'

# unlock, just to be sure
hc unlock

# set output for display currently i just setup my xorg.conf correctly
# hc spawn xrandr --output DP-0 --mode 5120x1440 --primary

# init monitors either manually or with detetc_monitors
#hc detect_monitors

#xrandr --output HDMI-1 --mode 5120x1440 --rate 60 --right-of DP-2
#xrandr --output HDMI-0 --primary --mode 1920x1080 --pos 7680x0 --rotate normal --output DP-0 --mode 2560x1440 --pos 0x0 --rotate normal --output DP-1 --off --output DP-2 --mode 5120x1440 --pos 2560x0 --rotate normal --output DP-3 --off --output DP-4 --off --output DP-5 --off
# xrandr --output HDMI-0 --off --rotate normal --output DP-0 --off --output DP-1 --off --output DP-4 --mode 5120x1440 --pos 0x0 --rotate normal --output DP-3 --off --output DP-4 --off --output DP-5 --off

# sleep 3
# hc set_monitors 1920x1080+0+0 1110x1440+1920+0 2900x1400+3030+40 1110x1440+5930+0


# WIP auto monitor config
sh ~/dotfiles/herbstluftwm/auto-monitor-config.sh
# currently with an additional 4k screen to edit videos on
# hc set_monitors 1920x1080+0+0 1110x1440+1920+0 2900x1400+3030+40 1110x1440+5930+0 3840x2160+7040+0
# only main monitor
# hc set_monitors 1110x1440+0+0 2900x1400+1110+40 1110x1440+4010+0

hc set frame_gap 10
hc attr theme.border_width 10
#herbstclient set window_gap 10
hc spawn picom
#hc spawn pkill '^redshift$' && sleep 10s && redshift-gtk -P &
# set wallpaper either i use feh or nitrogen
# hc spawn feh --bg-scale ~/walls/beach.jpg
hc spawn feh --bg-scale Downloads/mike-yukhtenko-wfh8dDlNFOk-unsplash.jpg
hc spawn nitrogen --restore &
hc spawn sh $HOME/.config/polybar/launch.sh
hc spawn /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
# hc spawn plank

# monitor paddings set to 0 as i just set the monitor positions accordingly
hc pad 3 0 0 0 0
hc pad 2 0 0 0 0
hc pad 1 0 0 0 0
hc pad 0 0 0 0 0



# create a panel for each monitor, i might add that for swapping tags
#panel=~/.config/herbstluftwm/panel.sh
#[ -x "$panel" ] || panel=/etc/xdg/herbstluftwm/panel.sh
#for monitor in $(hc list_monitors | cut -d: -f1) ; do
#    # start it on each monitor
#    "$panel" $monitor &
#done


# indicate multiple max layout windows not working but nice idea
# hc -i focus_changed | \
#     while read hook name winid
#     do
#         case $hook in
#             focus_changed) \
#                 tag=$(hc list_monitors | cut -d' ' -f5 | sed "s/
#                 -- \"//g")
#                 hc attr theme.active.color "#7a8f65"
#                 [[ -n $(hc layout | grep "FOCUS" | grep "max") ]]
#                 -- &
#                 hc compare tags.by-name.$tag.curframe_wcount gt 1
#                 ~~ &
#                 hc attr theme.active.color "#0056bc" & ;;
#         esac
#     done
// enable compose key
hc spawn setxkbmap -option compose:menu
