#!/usr/bin/env bash

# this is a simple config for herbstluftwm

hc() {
    herbstclient "$@"
}

hc emit_hook reload

xsetroot -solid '#5A8E3A'

# remove all existing keybindings
hc keyunbind --all

# keybindings
# if you have a super key you will be much happier with Mod set to Mod4
#Mod=Mod1    # Use alt as the main modifier
Mod=Mod4   # Use the super key as the main modifier

hc keybind $Mod-Shift-e quit
hc keybind $Mod-Shift-r reload
hc keybind $Mod-Shift-q close
#hc keybind $Mod-Return spawn gnome-terminal # use your $TERMINAL with xterm as fallback
hc keybind $Mod-Return termite # use your $TERMINAL with xterm as fallback
# hc keybind $Mod-d spawn rofi -width 1800 -fg "#B0E670" -bg "#2c303b" -hlfg "#14161F" -hlbg "#B0E670" -bc "#2c203b" -location 0 -lines 19 -bw 0 -font "MonacoB 16" -padding 15 -separator-style none -opacity 95 -show drun -modi run,drun,window -show-icons -sidebar-mode
hc keybind $Mod-d spawn rofi -show drun
hc keybind $Mod-y spawn sh ~/.config/rofi/power.sh

# basic movement
# focusing clients
hc keybind $Mod-Left  focus left
hc keybind $Mod-Down  focus down
hc keybind $Mod-Up    focus up
hc keybind $Mod-Right focus right
hc keybind $Mod-h     focus left
hc keybind $Mod-j     focus down
hc keybind $Mod-k     focus up
hc keybind $Mod-l     focus right

# moving clients
hc keybind $Mod-Shift-Left or / shift left / \
    chain , lock , shift_to_monitor -l , focus_monitor -l , unlock
hc keybind $Mod-Shift-Down  or / shift down / \
    chain , lock , shift_to_monitor -d , focus_monitor -d , unlock
hc keybind $Mod-Shift-Up    or / shift up / \
    chain , lock , shift_to_monitor -u , focus_monitor -u , unlock
hc keybind $Mod-Shift-Right or / shift right / \
    chain , lock , shift_to_monitor -r , focus_monitor -r , unlock
#hc keybind $Mod-Shift-h     shift left
#hc keybind $Mod-Shift-j     shift down
#hc keybind $Mod-Shift-k     shift up
#hc keybind $Mod-Shift-l     shift right

# splitting frames
# create an empty frame at the specified direction
hc keybind $Mod-u       split   bottom  0.5
hc keybind $Mod-o       split   right   0.5
# let the current frame explode into subframes
hc keybind $Mod-Control-space split explode

# resizing frames
resizestep=0.05
hc keybind $Mod-Control-h       resize left +$resizestep
hc keybind $Mod-Control-j       resize down +$resizestep
hc keybind $Mod-Control-k       resize up +$resizestep
hc keybind $Mod-Control-l       resize right +$resizestep
hc keybind $Mod-Control-Left    resize left +$resizestep
hc keybind $Mod-Control-Down    resize down +$resizestep
hc keybind $Mod-Control-Up      resize up +$resizestep
hc keybind $Mod-Control-Right   resize right +$resizestep

hc keybind $Mod-Shift-space floating toggle

# tags
tag_names=( {1..9} )
tag_keys=( {1..9} 0 )

hc rename default "${tag_names[0]}" || true
for i in ${!tag_names[@]} ; do
    hc add "${tag_names[$i]}"
    key="${tag_keys[$i]}"
    if ! [ -z "$key" ] ; then
        hc keybind "$Mod-$key" use_index "$i"
        hc keybind "$Mod-Shift-$key" move_index "$i"
    fi
done

# cycle through tags
hc keybind $Mod-period use_index +1 --skip-visible
hc keybind $Mod-comma  use_index -1 --skip-visible

# layouting
hc keybind $Mod-r remove
hc keybind $Mod-s floating toggle
hc keybind $Mod-f fullscreen toggle
hc keybind $Mod-p pseudotile toggle
# The following cycles through the available layouts within a frame, but skips
# layouts, if the layout change wouldn't affect the actual window positions.
# I.e. if there are two windows within a frame, the grid layout is skipped.
hc keybind $Mod-space                                                           \
            or , and . compare tags.focus.curframe_wcount = 2                   \
                     . cycle_layout +1 vertical horizontal max vertical grid    \
               , cycle_layout +1

# mouse
hc mouseunbind --all
hc mousebind $Mod-Button1 move
# hc mousebind $Mod-Button2 zoom
hc mousebind $Mod-Button3 resize

# focus
hc keybind $Mod-BackSpace   cycle_monitor
hc keybind $Mod-Tab         cycle_all +1
hc keybind $Mod-Shift-Tab   cycle_all -1
hc keybind $Mod-c cycle
hc keybind $Mod-i jumpto urgent

# theme
hc attr theme.tiling.reset 1
hc attr theme.floating.reset 1
hc set frame_border_active_color '#222222'
hc set frame_border_normal_color '#101010'
hc set frame_bg_normal_color '#565656'
hc set frame_bg_active_color '#FB8C00'
hc set frame_border_width 1
hc set always_show_frame 1
hc set frame_bg_transparent 1
hc set frame_transparent_width 5
hc set frame_gap 4

hc attr theme.active.color '#FB8C00'
hc attr theme.normal.color '#454545'
hc attr theme.urgent.color orange
hc attr theme.inner_width 1
hc attr theme.inner_color black
hc attr theme.border_width 3
hc attr theme.floating.border_width 4
hc attr theme.floating.outer_width 1
hc attr theme.floating.outer_color black
hc attr theme.active.inner_color '#3E4A00'
hc attr theme.active.outer_color '#3E4A00'
hc attr theme.background_color '#141414'

hc set window_gap 0
hc set frame_padding 0
hc set smart_window_surroundings 0
hc set smart_frame_surroundings 0
hc set mouse_recenter_gap 0


# Media
hc keybind XF86AudioRaiseVolume spawn changeVolume 2dB+ unmute
hc keybind XF86AudioLowerVolume spawn changeVolume 2dB- unmute



# rules
hc unrule -F
#hc rule class=XTerm tag=3 # move all xterms to tag 3
hc rule focus=on # normally focus new clients
#hc rule focus=off # normally do not focus new clients
# give focus to most common terminals
#hc rule class~'(.*[Rr]xvt.*|.*[Tt]erm|Konsole)' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' pseudotile=on
hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK|DESKTOP)' manage=off

hc set tree_style '╾│ ├└╼─┐'

# unlock, just to be sure
hc unlock


hc spawn pkill compton
# do multi monitor setup here, e.g.:
# hc set_monitors 1280x1024+0+0 1280x1024+1280+0
# or simply:

# set output for display

# hc spawn xrandr --output DP-0 --mode 5120x1440 --primary
#hc spawn xrandr --output DP-2 --mode 5120x1440 --primary
#hc spawn xrandr --output DP-1 --mode 1920x1080 --pos 0x0 --rotate inverted
# default just show normal montior layout

#hc detect_monitors

#hc keybind $Mod-m set_monitors 1920x1080+0+0 1280x1440+0+1080 2560x1440+1280+1080 1280x1440+3840+1080
#hc keybind $Mod-b set_monitors 1920x1080+0+0 1110x1440+0+1080 2900x1440+1110+1080 1110x1440+4010+1080
#hc keybind $Mod-n set_monitors 1920x1080+0+0 5120x1440+0+1080
#init monitors

# 3 virtual monitors on the ultrawide
#hc keybind $Mod-h set_monitors 1110x1440+0+1080 1110x1440+4010+1080 2900x1440+1110+1080 1920x1080+0+0 
# normal 16x9 center
#hc keybind $Mod-m set_monitors 1280x1440+0+0 2560x1440+1280+0 1280x1440+3840+0
# ultrawide in the center
hc set_monitors 1110x1440+0+0 2900x1440+1110+0 1110x1440+4010+0
# single screen
#hc keybind $Mod-n set_monitors 5120x1440+0+0
# small 27inch screen
#hc keybind $Mod-v set_monitors 2560x1440+0+0
#hc keybind $Mod-h set_monitors 1760x1440+0+0

#hc keybind $Mod-h set_monitors 1110x1440+0+1080 1110x1440+4010+1080 2900x1440+1110+1080 1920x1080+0+0 

# hc set_monitors 1280x1440+0+0 2560x1440+1280+0 1280x1440+3840+0

hc set frame_gap 10
hc attr theme.border_width 10
#herbstclient set window_gap 10
hc spawn compton
hc spawn feh --bg-scale ~/walls/beach.jpg
hc spawn sh $HOME/.config/polybar/launch.sh

hc pad 3 10 10 10 10
hc pad 2 10 10 10 10
hc pad 1 10 10 40 10
hc pad 0 10 10 10 10



# find the panel
#panel=~/.config/herbstluftwm/panel.sh
#[ -x "$panel" ] || panel=/etc/xdg/herbstluftwm/panel.sh
#for monitor in $(hc list_monitors | cut -d: -f1) ; do
#    # start it on each monitor
#    "$panel" $monitor &
#done


# indicate multiple max layout windows
# hc -i focus_changed | \
#     while read hook name winid
#     do
#         case $hook in
#             focus_changed) \
#                 tag=$(hc list_monitors | cut -d' ' -f5 | sed "s/
#                 -- \"//g")
#                 hc attr theme.active.color "#7a8f65"
#                 [[ -n $(hc layout | grep "FOCUS" | grep "max") ]]
#                 -- &
#                 hc compare tags.by-name.$tag.curframe_wcount gt 1
#                 ~~ &
#                 hc attr theme.active.color "#0056bc" & ;;
#         esac
#     done

## no frame borders
# hc set window_gap 30
# hc set frame_gap -30
# hc set frame_padding 0
# hc set smart_window_surroundings 0
# hc set smart_frame_surroundings 0
# hc pad 0 15 15 75 15
# hc pad 1 15 15 75 15
# hc attr theme.tiling.reset 1
# hc attr theme.floating.reset 1
# hc set frame_border_width 0
# hc set always_show_frame 0
# hc set frame_bg_transparent 1
# hc set frame_transparent_width 0
